#应用服务WEB访问端口
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20010511dx
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis服务
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#配置阿里云OSS对象存储器
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tPccqm6apAQZE4PLvK4
    accessKeySecret: BF6ShuNQzGXpgdBSzak1mEuVtmpYog
    bucketName: expectremember
#开启事务管理日志
logging:
  level:
    org.springframework.jdbc.support.jdbcTransactionManager: debug